In [32]:
import pandas as pd

In [33]:
data = pd.read_csv("movies.csv")
data

,Unnamed: 0,Title,Subtitle,Realise Time
0,0,Oh My Ghost! The Fierce Escape from Covid-19 (...,RAW,2024-07-10 07:09:38
1,1,Bear Man (2023),SUB,2024-07-10 06:53:47
2,2,Kamen Rider 555 20th: Paradise Regained (2024),SUB,2024-07-09 21:29:43
3,3,Following (2024),RAW,2024-07-08 15:17:59
4,4,Yumi's Cells the Movie (2024),SUB,2024-07-07 23:26:59
...,...,...,...,...
715,715,Kill Me Now (2022),RAW,2022-11-01 09:10:38
716,716,Confidential Assignment 2: International (2022),SUB,2022-10-30 18:13:04
717,717,Leio (2022),SUB,2022-10-28 20:07:54
718,718,FOX LOVE (2022),SUB,2022-10-28 09:06:33
719,719,The Mad Sword (2021),SUB,2022-10-28 09:05:28

In [34]:
data.drop(['Unnamed: 0'], axis=1, inplace=True)
data

,Title,Subtitle,Realise Time
0,Oh My Ghost! The Fierce Escape from Covid-19 (...,RAW,2024-07-10 07:09:38
1,Bear Man (2023),SUB,2024-07-10 06:53:47
2,Kamen Rider 555 20th: Paradise Regained (2024),SUB,2024-07-09 21:29:43
3,Following (2024),RAW,2024-07-08 15:17:59
4,Yumi's Cells the Movie (2024),SUB,2024-07-07 23:26:59
...,...,...,...
715,Kill Me Now (2022),RAW,2022-11-01 09:10:38
716,Confidential Assignment 2: International (2022),SUB,2022-10-30 18:13:04
717,Leio (2022),SUB,2022-10-28 20:07:54
718,FOX LOVE (2022),SUB,2022-10-28 09:06:33
719,The Mad Sword (2021),SUB,2022-10-28 09:05:28